name: pytest-check

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.0]

    steps:
      - name: install poetry
        run:  pip install poetry
      - name: install dependencies
        run:
          make install
      - name: run pytest
        run:
          make test
